

export component Visualizer inherits HorizontalLayout {

    in property <bool> is-playing;
    in property <int> bar-count;
    in property <length> parent-width;
    in property <color> text-color;
    in property <angle> phase: 30deg;

    x: 48px;
    y: 0;
    width: root.parent-width - 48px;
    height: 100%;
    spacing: 2px;
    opacity: root.is-playing ? 1 : 0;
    animate opacity { duration: 1s; }
    for i in bar-count: Rectangle {
        width: (parent.width / bar-count);
        height: 100%;
        VerticalLayout {
            alignment: end;
            Rectangle {
                // Draws a sine wave animation
                // IMPORTANT!: only use animation-tick() when actually playing to prevent constant Skia texture reallocations
                // causing memory leaks
                height: root.is-playing ? 8px + 20px * (0.5 + 0.5 * sin((animation-tick() / 5ms) * 1deg + (i * root.phase))) : 14px;
                background: root.text-color;
                opacity: 0.4;
                border-radius: 2px;
            }
        }
    }
}
