// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

export global Icons {
    out property <image> arrow_back: @image-url("arrow_back.svg");
    out property <image> arrow_drop_down: @image-url("arrow_drop_down.svg");
    out property <image> arrow_drop_up: @image-url("arrow_drop_up.svg");
    out property <image> arrow_right: @image-url("arrow_right.svg");
    out property <image> battery_0_bar: @image-url("battery_0_bar.svg");
    out property <image> battery_1_bar: @image-url("battery_1_bar.svg");
    out property <image> battery_2_bar: @image-url("battery_2_bar.svg");
    out property <image> battery_3_bar: @image-url("battery_3_bar.svg");
    out property <image> battery_4_bar: @image-url("battery_4_bar.svg");
    out property <image> battery_5_bar: @image-url("battery_5_bar.svg");
    out property <image> battery_6_bar: @image-url("battery_6_bar.svg");
    out property <image> battery_alert: @image-url("battery_alert.svg");
    out property <image> battery_charging_20: @image-url("battery_charging_20.svg");
    out property <image> battery_charging_30: @image-url("battery_charging_30.svg");
    out property <image> battery_charging_80: @image-url("battery_charging_80.svg");
    out property <image> battery_charging_90: @image-url("battery_charging_90.svg");
    out property <image> battery_full: @image-url("battery_full.svg");
    out property <image> battery_unknown: @image-url("battery_unknown.svg");
    out property <image> bluetooth: @image-url("bluetooth.svg");
    out property <image> bluetooth_connected: @image-url("bluetooth_connected.svg");
    out property <image> bluetooth_disabled: @image-url("bluetooth_disabled.svg");
    out property <image> bluetooth_searching: @image-url("bluetooth_searching.svg");
    out property <image> bolt: @image-url("bolt.svg");
    out property <image> calendar_today: @image-url("calendar_today.svg");
    out property <image> check: @image-url("check.svg");
    out property <image> chevron_backward: @image-url("chevron_backward.svg");
    out property <image> chevron_forward: @image-url("chevron_forward.svg");
    out property <image> close: @image-url("close.svg");
    out property <image> edit: @image-url("edit.svg");
    out property <image> indeterminate_question_box: @image-url("indeterminate_question_box.svg");
    out property <image> keyboard: @image-url("keyboard.svg");
    out property <image> lan: @image-url("lan.svg");
    out property <image> menu: @image-url("menu.svg");
    out property <image> network_wifi_1_bar: @image-url("network_wifi_1_bar.svg");
    out property <image> network_wifi_2_bar: @image-url("network_wifi_2_bar.svg");
    out property <image> network_wifi_3_bar: @image-url("network_wifi_3_bar.svg");
    out property <image> remove: @image-url("remove.svg");
    out property <image> schedule: @image-url("schedule.svg");
    out property <image> signal_wifi_4_bar: @image-url("signal_wifi_4_bar.svg");
    out property <image> signal_wifi_bad: @image-url("signal_wifi_bad.svg");
    out property <image> signal_wifi_off: @image-url("signal_wifi_off.svg");
    out property <image> signal_wifi_statusbar_not_connected: @image-url("signal_wifi_statusbar_not_connected.svg");
    out property <image> signal_wifi_statusbar_null: @image-url("signal_wifi_statusbar_null.svg");
    out property <image> volume_down: @image-url("volume_down.svg");
    out property <image> volume_off: @image-url("volume_off.svg");
    out property <image> volume_up: @image-url("volume_up.svg");
}
