// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

export global Icons {
    out property <image> battery_0_bar: @image-url("battery_0_bar.svg");
    out property <image> battery_1_bar: @image-url("battery_1_bar.svg");
    out property <image> battery_2_bar: @image-url("battery_2_bar.svg");
    out property <image> battery_3_bar: @image-url("battery_3_bar.svg");
    out property <image> battery_4_bar: @image-url("battery_4_bar.svg");
    out property <image> battery_5_bar: @image-url("battery_5_bar.svg");
    out property <image> battery_6_bar: @image-url("battery_6_bar.svg");
    out property <image> battery_alert: @image-url("battery_alert.svg");
    out property <image> battery_charging_20: @image-url("battery_charging_20.svg");
    out property <image> battery_charging_30: @image-url("battery_charging_30.svg");
    out property <image> battery_charging_80: @image-url("battery_charging_80.svg");
    out property <image> battery_charging_90: @image-url("battery_charging_90.svg");
    out property <image> battery_full: @image-url("battery_full.svg");
    out property <image> battery_unknown: @image-url("battery_unknown.svg");
    out property <image> bluetooth: @image-url("bluetooth.svg");
    out property <image> bluetooth_connected: @image-url("bluetooth_connected.svg");
    out property <image> bluetooth_disabled: @image-url("bluetooth_disabled.svg");
    out property <image> bluetooth_searching: @image-url("bluetooth_searching.svg");
    out property <image> bolt: @image-url("bolt.svg");
    out property <image> indeterminate_question_box: @image-url("indeterminate_question_box.svg");
    out property <image> lan: @image-url("lan.svg");
    out property <image> music_note_2: @image-url("music_note_2.svg");
    out property <image> network_wifi_1_bar: @image-url("network_wifi_1_bar.svg");
    out property <image> network_wifi_2_bar: @image-url("network_wifi_2_bar.svg");
    out property <image> network_wifi_3_bar: @image-url("network_wifi_3_bar.svg");
    out property <image> pause: @image-url("pause.svg");
    out property <image> play_arrow: @image-url("play_arrow.svg");
    out property <image> signal_wifi_4_bar: @image-url("signal_wifi_4_bar.svg");
    out property <image> signal_wifi_bad: @image-url("signal_wifi_bad.svg");
    out property <image> signal_wifi_off: @image-url("signal_wifi_off.svg");
    out property <image> signal_wifi_statusbar_not_connected: @image-url("signal_wifi_statusbar_not_connected.svg");
    out property <image> signal_wifi_statusbar_null: @image-url("signal_wifi_statusbar_null.svg");
    out property <image> skip_next: @image-url("skip_next.svg");
    out property <image> skip_previous: @image-url("skip_previous.svg");
    out property <image> volume_down: @image-url("volume_down.svg");
    out property <image> volume_off: @image-url("volume_off.svg");
    out property <image> volume_up: @image-url("volume_up.svg");
}
