
import {
    MaterialPalette,
} from "../../../material-1.0/ui/styling/material_palette.slint";
import { Icons } from "../../../material-1.0/ui/icons/icons.slint";
import { HorizontalBox } from "std-widgets.slint";

export struct ActiveWindowData {
    app: string,
    window_title: string,
    icon: image,
    active_monitor: bool,
}

export component ActiveWindow inherits Rectangle {
    in property <ActiveWindowData> activeWindow;

    visible: root.activeWindow.active_monitor; // TODO: make config that dynamically changes this

    clip: true;
    width: 400px;
    height: 48px;
    background: MaterialPalette.surface_variant;
    border-radius: 8px;

    activeWindow := TouchArea {
        width: 100%;
        height: 100%;
    }

    VerticalLayout {
        alignment: center;
        HorizontalLayout {
            VerticalLayout {
                alignment: center;
                padding-left: 8px;
                padding-right: 8px;
                Rectangle {
                    border-radius: 8px;
                    width: 32px;
                    height: 32px;
                    clip: true;

                    Image {
                        width: 100%;
                        height: 100%;
                        source: root.activeWindow.icon;
                        image-fit: cover;
                    }

                    // unknown app indicator
                Image {
                        visible: root.activeWindow.icon.width == 0;
                        width: 100%;
                        height: 100%;
                        source: Icons.indeterminate_question_box;
                    }
                }
            }

            VerticalLayout {
                horizontal-stretch: 1;

                Text {
                    font-weight: 400;
                    font-size: 8px;
                    color: MaterialPalette.on_surface_variant;
                    text: root.activeWindow.app;
                }

                Text {
                    font-weight: 500;
                    font-size: 14px;
                    color: MaterialPalette.on_surface;
                    text: root.activeWindow.window_title;
                }
            }
        }
    }

    settingsButton := Image {
        opacity: activeWindow.has-hover ? 1 : 0;
        source: Icons.settings_applications;
        x: activeWindow.has-hover ? parent.width - settingsButton.width : parent.width - settingsButton.width + 8px;
        animate x, opacity {
            duration: 200ms;
            easing: ease-in-out;
        }
    }
}
