
export struct ClockState {
    time: string,
    date: string,
}

export component Clock {
    in-out property <ClockState> state: {
        time: "00:00",
        date: "02/01/2025",
    };

    // Component sizing - fits content
    VerticalLayout {
        padding-left: 4px;
        padding-right: 4px;
        alignment: center;

        Text {
            text: root.state.date;
            color: #aaa;
            font-size: 10px;
            horizontal-alignment: center;
            vertical-alignment: center;
        }

        Text {
            text: root.state.time;
            color: #fff;
            font-size: 14px;
            horizontal-alignment: center;
            vertical-alignment: center;
            font-weight: 600;
        }
    }
}
