import { Clock, ClockState } from "clock.slint";
import { TaskbarBattery, BatteryData, BatteryState } from "battery.slint";
import { TaskbarVolume } from "volume.slint";
import {
    MaterialPalette,
} from "../../../material-1.0/ui/styling/material_palette.slint";
import { Palette } from "std-widgets.slint";
import { TaskbarNetwork } from "network.slint";
import { NetworkState } from "network.slint";
import { TaskbarBluetooth } from "bluetooth.slint";
import { BluetoothState } from "bluetooth.slint";
import { MediaData } from "media/mediaDataStruct.slint";
import { MediaWidget } from "media.slint";
import {
    StateLayerArea,
} from "../../../material-1.0/ui/components/state_layer.slint";
import {
    MaterialStyleMetrics,
} from "../../../material-1.0/ui/styling/material_style_metrics.slint";
import {
    TaskbarWorkspaces,
    WorkspaceData,
    WorkspaceState,
} from "workspaces.slint";
import { ActiveWindow } from "activeWindow.slint";

export { WorkspaceData, WorkspaceState, MediaData }

export component Taskbar inherits Window {
    init => {
        Palette.color-scheme = ColorScheme.dark; // move this to rust when user config is implemented
    }

    // State properties
    in-out property <ClockState> clock-state: {
        time: "00:00",
        date: "Mon, Jan 1",
    };

    in-out property <BatteryData> battery-data: {
        percentage: 0,
        state: BatteryState.Unknown,
        time_remaining: "",
    };

    in-out property <int> volume: 0;

    in-out property <bool> has-battery: false;
    in-out property <NetworkState> network-state: NetworkState.NotConnected;

    in-out property <BluetoothState> bluetooth-state: BluetoothState.Off;
    in-out property <bool> has-bluetooth: false;

    in-out property <image> appIcon;

    // Workspaces
    in-out property <[WorkspaceData]> workspaces: [];
    callback workspace-clicked(int);  // Called when workspace is clicked

    // Media
    in-out property <MediaData> media-data: {
        has_media: false,
        text_color: #ffffff,
    };
    callback media-play-pause();
    callback media-next();
    callback media-prev();
    callback media-seek(float);

    callback update-clock();
    Timer {
        interval: 1s;
        running: true;
        triggered => {
            root.update-clock();
        }
    }

    // Main window styling
    background: MaterialPalette.surface;
    height: 48px;

    // Main layout: 3-section row (left | center | right)
    HorizontalLayout {
        padding-left: 8px;
        padding-right: 8px;
        spacing: 8px;

        // === LEFT SECTION ===
        

        HorizontalLayout {
            alignment: start;

            VerticalLayout {
                alignment: center;
                horizontal-stretch: 1;
                TaskbarWorkspaces {
                    workspaces: root.workspaces;
                    workspace-clicked(id) => {
                        root.workspace-clicked(id);
                    }
                }
            }

            MediaWidget {
                visible: root.media-data.has-media;
                data: root.media-data;
                play-pause => {
                    root.media-play-pause();
                }
                next => {
                    root.media-next();
                }
                prev => {
                    root.media-prev();
                }
                seek(x) => {
                    root.media-seek(x);
                }
            }
        }

        // === CENTER SECTION ===
        HorizontalLayout {
            alignment: center;
            ActiveWindow {
                appIcon: root.appIcon;
            }
        }

        // === RIGHT SECTION ===
        HorizontalLayout {
            spacing: 8px;
            alignment: end;

            if root.has-battery: TaskbarBattery {
                data: root.battery-data;
            }

            Clock {
                state: root.clock-state;
            }

            VerticalLayout {
                alignment: center;
                HorizontalLayout {
                    spacing: 0;

                    TaskbarVolume {
                        volume: root.volume;
                    }

                    TaskbarNetwork {
                        state: root.network-state;
                    }

                    if root.has-bluetooth: TaskbarBluetooth {
                        state: root.bluetooth-state;
                    }
                }
            }
        }
    }
}
