import { Icons } from "../../../material-1.0/ui/icons/icons.slint";
import {
    BaseButton,
} from "../../../material-1.0/ui/components/base_button.slint";
import {
    MaterialPalette,
} from "../../../material-1.0/ui/styling/material_palette.slint";
import {
    MaterialStyleMetrics,
} from "../../../material-1.0/ui/styling/material_style_metrics.slint";

export component TaskbarVolume inherits BaseButton {
    in property <int> volume;

    color: root.volume == 0 ? MaterialPalette.error : MaterialPalette.on_surface;

    button_horizontal_padding: MaterialStyleMetrics.padding_4;
    button_vertical_padding: MaterialStyleMetrics.padding_4;
    height: MaterialStyleMetrics.size_40;
    border_radius: MaterialStyleMetrics.border_radius_28;
    spacing: MaterialStyleMetrics.spacing_4;

    icon: {
        if root.volume == 0 {
            return Icons.volume_off;
        } else if root.volume < 50 {
            return Icons.volume_down;
        } else {
            return Icons.volume_up;
        }
    };
    icon_size: MaterialStyleMetrics.icon_size_24;

    text: {
        if root.volume == 0 {
            return "Muted";
        } else {
            return root.volume + "%";
        }
    };
}
