import { MediaData } from "mediaDataStruct.slint";
import { Carousel } from "../../../components/carousel.slint";

export component StateMetadata inherits VerticalLayout {
    in property <MediaData> data;
    in property <bool> active;
    padding: 4px;
    padding-left: 8px;
    padding-right: 8px;

    Rectangle {
        clip: true;
        vertical-stretch: 1;

        Carousel {
            width: 100%;
            height: 100%;
            ramp: 2000ms;
            hold: 2000ms;
            active: root.active;
            parent-width: parent.width;

            Text {
                text: root.data.title;
                color: root.data.text-color;
                font-size: 14px;
                font-weight: 600;
                overflow: elide;
            }
        }
    }

    Rectangle {
        clip: true;
        vertical-stretch: 1;

        Carousel {
            width: 100%;
            height: 100%;
            ramp: 2000ms;
            hold: 2000ms;
            active: root.active;
            parent-width: parent.width;

            Text {
                text: root.data.artist;
                color: root.data.text-color;
                font-size: 12px;
                font-weight: 600;
                vertical-alignment: center;
                vertical-stretch: 1;
            }

            Text {
                text: " - ";
                color: root.data.text-color;
                font-size: 12px;
                vertical-alignment: center;
                vertical-stretch: 1;
            }

            Text {
                text: root.data.album;
                color: root.data.text-color;
                font-size: 12px;
                vertical-alignment: center;
                vertical-stretch: 1;
            }
        }
    }
}
