

import { ProgressBar } from "../../../components/progressBar.slint";
import { MediaData } from "mediaDataStruct.slint";
import { TimeFormatting } from "timeFormatting.slint";
import {
    MaterialPalette,
} from "../../../../material-1.0/ui/styling/material_palette.slint";

export component StateNormal inherits VerticalLayout {
    in property <MediaData> data;

    padding: 4px;
    padding-left: 8px;
    padding-right: 8px;
    alignment: center;

    Rectangle {
        height: 20px;
        clip: true;
        Text {
            text: root.data.title + " • " + root.data.artist;
            color: root.data.text-color;
            width: parent.width;
            font-size: 13px;
            font-weight: 600;
            horizontal-alignment: center;
            overflow: elide;
        }
    }

    Rectangle {
        height: 16px;

        ProgressBar {
            intractable: false;
            background-color: root.data.text-color.with-alpha(0.3);
            progressed-color: MaterialPalette.primary;
            position_secs: root.data.position_secs;
            length_secs: root.data.length_secs;
        }
    }
}
